### PR TITLE
Fixed plugin for IDA 7.4 and Python3

### PR DESCRIPTION
**Pull request by evolution536**
I changed the script to work with IDA 7.4 (without compatibility layer) and Python3.

### CODE REVIEW

**Comment by Ga-ryo** [comment]
#6

**Comment by Ga-ryo** [comment]
@evolution536 
Thank you!
Most patches are working well in my environment too.
But `super(FuzzySearchForm, self).cEChooser` doesn't work.
How about just adding below code to FuzzySearchForm.\_\_init\_\_ function? ( is it working in python3? )
I wanna keep backward compatibility, because I'm poor man. 😢
```
        try:
          self.cEChooser = super().cEChooser #super() will raise exception in python2
        except:
          pass
```

**Comment by evolution536** [comment]
I added this code to the init function, and it works for me. Feel free to change it however you think it should be. 😄

**Comment by Ga-ryo** [comment]
I mean
Add above code instead of changing self to super()

**Comment by evolution536** [comment]
Like this? It works in IDA 7.4. :)

**Comment by Ga-ryo** [comment]
@evolution536 
Yes, thank you :)

**Pull request merged**
